### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by movrack** [mgechev/aspect.js-angular#1]
Deprecated in favor of what ?

**Comment by mgechev** [comment]
You can access the `Injector` by injecting it into a woven service's constructor:

``` ts
@Wove()
class Foo {
  constructor(private _injector: Injector) {}
}
```

Although it's not very clean (there's still some coupling between the aspect and the target), you can later access the injector by using:

``` ts
@beforeMethod(...)
log(metadata: Metadata) {
  metadata.method.context._injector;
}
```
